### ISSUE TITLE
Inquiry about Repository Status and Contribution Opportunities

### ISSUE THREAD

**Issue by dingxin-tech** [prestodb/presto-alibaba-maxcompute-connector#3]
Hello,

I've noticed that [prestodb/presto-alibaba-maxcompute-connector](https://github.com/prestodb/presto-alibaba-maxcompute-connector) hasn't seen any activity for a while. I wanted to inquire if this repository is still being maintained or if it has been deprecated.

As an active user and developer interested in the MaxCompute connector, I would like to offer my assistance. I would love to contribute to the project and help keep it up to date.

Could you please let me know if the repository is open for contributions? If so, I would like to request commit access so that I can make direct contributions to the codebase.

Thank you for your time and consideration. I look forward to your response and hope to contribute to the continued success of this project.

Best regards,
Jason

**Comment by tdcmeehan** [comment]
Hello @dingxin-tech.  This was intended to be added as a third party connector, outside of the main repository.  It became blocked on setting up a release pipeline, but now we have that, and can open source this plugin.  If you have working code that integrates with Alibaba's MaxCompute connector, we'll be happy to merge it in this repository.

**Comment by dingxin-tech** [comment]
Hello @tdcmeehan. I am very enthusiastic about implementing an Alibaba MaxCompute connector. Integrating it into this repository might be a good option. However, I'm concerned about ensuring that the version I implement can evolve alongside new releases of PrestoDB. I've noticed that besides this repository, other connectors are housed within the main PrestoDB repository. Do you recommend that this connector be maintained in this separate repository rather than in the main repository?

**Comment by tdcmeehan** [comment]
@dingxin-tech actually, we've begun to move connectors outside of the main repository (see https://github.com/prestodb/presto/issues/22684 which was just raised today).  Going forward, we'll probably be introducing more and more connectors which are within the Prestodb org, but in their own repository.  Hope this helps!

**Comment by wanglinsong** [comment]
@dingxin-tech I could help set up the release pipeline.
